### ISSUE TITLE
Carousel not working after cleanup

### ISSUE THREAD

**Issue by anishsheela** [anishsheela/owlcarousel#3]
Carousel is not getting loaded after the cleanup.

**Comment by Oligerd** [comment]
Hi!
You did a little mistake in module. It have to be that:
`$attached = [
    '#attached' => ['library' => ['owlcarousel/owlcarousel']],
  ];`

**Comment by anishanilkumar** [comment]
Fixed on commit 74b9f11d5f31823f2e5126fdebda364e15550d96
